resource "tls_private_key" "ubuntu_private_key" {
  algorithm = "RSA"
  rsa_bits  = 4096

  provisioner "local-exec" {
    command = "mkdir -p .ssh"
  }

  provisioner "local-exec" { # Copy a "myKey.pem" to local computer.
    command = "echo '${tls_private_key.ubuntu_private_key.private_key_pem}' | tee ${path.cwd}/.ssh/myKey.pem"
  }

  provisioner "local-exec" {
    command = "chmod 600 ${path.cwd}/.ssh/myKey.pem"
  }
}

resource "proxmox_virtual_environment_container" "ubuntu_container" {
  description = "Managed by Terraform"
  node_name = "pve01"
  vm_id     = 1234
  tags        = ["terraform", "ubuntu"]

  initialization {
    hostname = "nextcloud"

    ip_config {
      ipv4 {
        address = "${var.container_ips}/${var.network_range}"
        gateway = var.gateway
      }
    }

    user_account {
      keys     = [trimspace(tls_private_key.ubuntu_private_key.public_key_openssh)]
      # password = random_password.ubuntu_vm_password.result
      password = "mypassword"
    }
  }

  network_interface {
    name = "veth0"
  }

  operating_system {
    template_file_id = proxmox_virtual_environment_download_file.ubuntu-24-04-standard_lxc_img.id
    type             = "ubuntu"
  }

  disk {
    datastore_id = "local-zfs"
    size = 25
  }

  cpu {
    cores = 2
  }

  memory {
    dedicated = 1024
  }

  startup {
    order      = "3"
    up_delay   = "60"
    down_delay = "60"
  }

  features {
    nesting = true
    fuse = true
  }

  unprivileged = true
}

resource "proxmox_virtual_environment_download_file" "ubuntu-24-04-standard_lxc_img" {
  content_type = "vztmpl"
  datastore_id = "local"
  node_name    = "pve01"
  file_name = "nextcloud-ubuntu-24.04-lxc.tar.zst"
  url          = "http://download.proxmox.com/images/system/ubuntu-24.04-standard_24.04-2_amd64.tar.zst"
}

resource "random_password" "ubuntu_container_password" {
  length           = 16
  override_special = "_%@"
  special          = true
}

# Ansible Section 

resource "ansible_host" "nextcloud" {
  name   = var.container_ips

  variables = {
    ansible_user                 = "root"
    ansible_ssh_private_key_file = "./.ssh/myKey.pem"
    ansible_python_interpreter   = "/usr/bin/python3"
    host_name                    = "nextcloud"
    greetings                    = "from host!"
    some                         = "variable"
    private_ip                   = var.container_ips
  }

}



# Export Terraform variable values to an Ansible var_file
resource "local_file" "tf_ansible_vars_file_new" {
  content = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.

    # tf_instance_ami: 
    # tf_aws_instance_controlplace_ip: 
    DOC
  filename = "./ansible/tf_ansible_vars_file.yaml"
}